[package]
name = "findomain"
version = "5.0.0"
authors = ["Eduard Tolosa <edu4rdshl@protonmail.com>"]
edition = "2018"
description = "The fastest and cross-platform subdomain enumerator, do not waste your time."
repository = "https://github.com/edu4rdshl/findomain"
license = "GPL-3.0-or-later"
keywords = ["discover-subdomains", "ct-logs", "search-subdomains", "enumerate-subdomains", "subdomain-scanner"]
readme = "README.md"

[dependencies]
serde = { version = "1.0.126", features = ["derive"] }
serde_derive = "1.0.126"
reqwest = { version = "0.11.3", features = ["blocking", "json", "gzip"] }
# trust-dns-resolver = { version = "0.20.2", features = ["dns-over-rustls"] }
trust-dns-resolver = { git = "https://github.com/Edu4rdSHL/trust-dns", branch = "main" }
clap = { version = "2.33.3", features = ["yaml"] }
lazy_static = "1.4.0"
rand = "0.8.3"
postgres = "0.19.1"
failure = "0.1.8"
rayon = "1.5.1"
config = { version = "0.11.0", features = ["yaml", "json", "toml", "hjson", "ini"] }
headless_chrome = { git = "https://github.com/Edu4rdSHL/rust-headless-chrome" }

[target.arm-unknown-linux-gnueabihf.dependencies]
openssl = { version = "0.10.34", features = ["vendored"] }

[target.aarch64-unknown-linux-gnu.dependencies]
openssl = { version = "0.10.34", features = ["vendored"] }

[target.armv7-unknown-linux-gnueabihf.dependencies]
openssl = { version = "0.10.34", features = ["vendored"] }

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
